services:
  router_a:
    build: .
    container_name: router_a
    privileged: true
    environment:
      MY_IP: "10.0.1.10"
      NEIGHBORS: "10.0.1.11,10.0.3.12"
      DIRECT_SUBNETS: "10.0.1.0/24,10.0.3.0/24"
    networks:
      net_ab:
        ipv4_address: 10.0.1.10
      net_ac:
        ipv4_address: 10.0.3.10

  router_b:
    build: .
    container_name: router_b
    privileged: true
    environment:
      MY_IP: "10.0.1.11"
      NEIGHBORS: "10.0.1.10,10.0.2.12"
      DIRECT_SUBNETS: "10.0.1.0/24,10.0.2.0/24"
    networks:
      net_ab:
        ipv4_address: 10.0.1.11
      net_bc:
        ipv4_address: 10.0.2.11

  router_c:
    build: .
    container_name: router_c
    privileged: true
    environment:
      MY_IP: "10.0.2.12"
      NEIGHBORS: "10.0.2.11,10.0.3.10"
      DIRECT_SUBNETS: "10.0.2.0/24,10.0.3.0/24"
    networks:
      net_bc:
        ipv4_address: 10.0.2.12
      net_ac:
        ipv4_address: 10.0.3.12

networks:
  net_ab:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
  net_bc:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
  net_ac:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.3.0/24
